### ISSUE TITLE
KeyError: (0, 96)

### ISSUE THREAD

**Issue by Pretexts** [beurtschipper/Depix#11]
INFO:root:Loading pixelated image from IMG_4324.JPG
INFO:root:Loading search image from images/searchimages/mac_burp.png
INFO:root:Finding color rectangles from pixelated space
INFO:root:Found 685 same color rectangles
INFO:root:671 rectangles left after moot filter
INFO:root:Found 44 different rectangle sizes
INFO:root:Finding matches in search image
INFO:root:Removing blocks with no matches
Traceback (most recent call last):
  File "/xxx/Depix/depix.py", line 52, in <module>
    pixelatedSubRectanges = dropEmptyRectangleMatches(rectangleMatches, pixelatedSubRectanges)
  File "/xxx/Depix/depixlib/functions.py", line 149, in dropEmptyRectangleMatches
    if len(rectangleMatches[(pixelatedSubRectange.x,pixelatedSubRectange.y)]) > 0:
KeyError: (0, 96)
![image](https://user-images.githubusercontent.com/29346963/101379522-52a7cd00-38ef-11eb-80b5-938721dba365.png)

**Comment by Busch** [comment]
Same issue here.

**Comment by beurtschipper** [comment]
Did you cut out the pixelized part of the image?

**Comment by Pretexts** [comment]
> 您是否切出了图像的像素化部分？

No, I didn't.

**Comment by Busch** [comment]
> Did you cut out the pixelized part of the image?

That fixed my issue. Thanks!
