### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by Babs84** [beurtschipper/Depix#2]
Your example isn't working for me, but worked with `python3` instead of `python`.

Maybe an issue ?

**Comment by onclave** [comment]
> Your example isn't working for me, but worked with `python3` instead of `python`.
> 
> 
> 
> Maybe an issue ?
> 
> 

@Babs84 it's because you have python 3.x installed on your system as `python3`. If python 3.x is available on any system as `python` on their system, this would work. This isn't an issue.
