### ISSUE TITLE
It takes too much time...

### ISSUE THREAD

**Issue by dingbinacm** [beurtschipper/Depix#23]
Only one image, it takes over 1hour, but still no feedback.No progress, no exception.

**Comment by kat953162** [comment]
I know this one, it's failed a task, if you ctrl-c you will see it skip to next tasks, and if you get an output at all, it will be the input image or something in the middle.

**Comment by beurtschipper** [comment]
Then try a smaller image or go optimize the algorithm instead of complaining about it in issue tickets.
