### ISSUE TITLE
Passing font parameter instead of search image

### ISSUE THREAD

**Issue by KonradLinkowski** [beurtschipper/Depix#3]
I thought that maybe it would be better to generate search images with the sequence on the fly for specified font.
Generating the image with different font would allow user to depix screenshot taken in another text editor just by knowing the font

**Comment by beurtschipper** [comment]
Yeah I started with that idea but it was too much work. I had problems generating proper fonts using the Pillow library, because you need to be able to set things like HSL, which proved to be difficult.
