### ISSUE TITLE
BUG (TypeError: 'int' object is not subscriptable)

### ISSUE THREAD

**Issue by tlhcelik** [beurtschipper/Depix#30]
INFO:root:Loading pixelated image from test.png
Traceback (most recent call last):
  File "depix.py", line 27, in <module>
    pixelatedImage = LoadedImage(pixelatedImagePath)
  File "C:\pixelate\depixlib\LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "C:\pixelate\depixlib\LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object is not subscriptable

**Comment by beurtschipper** [comment]
What kind of image are you loading? Is it a PNG or a JPEG?

**Comment by Nicklas2751** [comment]
I have the same error. My images are PNG.
```
python3 depix.py -p crypt.png -s data.png -o encrypted.png
INFO:root:Loading pixelated image from /home/me/crypt.png
Traceback (most recent call last):
  File "depix.py", line 27, in <module>
    pixelatedImage = LoadedImage(pixelatedImagePath)
  File "/home/me/Depix/depixlib/LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "/home/me/Depix/depixlib/LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object is not subscriptable
```

**Comment by tlhcelik** [comment]
> What kind of image are you loading? Is it a PNG or a JPEG?

python3 depix.py -p input.png -s debruinseq_notepad_Windows10_close.png -o **test.png**

**Comment by matgas23** [comment]
I have the same error.
```
python depix.py -p ..\pixelate.png -s .\images\searchimages\debruinseq_notepad_Windows10_close.png -o output4.png
INFO:root:Loading pixelated image from ..\pixelate.png
Traceback (most recent call last):
  File "D:\projects\depix_1\Depix\depix.py", line 27, in <module>
    pixelatedImage = LoadedImage(pixelatedImagePath)
  File "D:\projects\depix_1\Depix\depixlib\LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "D:\projects\depix_1\Depix\depixlib\LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object is not subscriptable
```

**Comment by beurtschipper** [comment]
Can one of you upload the image here? I'd like to check it out

**Comment by OrioPrisco** [comment]
![test](https://user-images.githubusercontent.com/47635210/102229078-a87e0580-3eeb-11eb-82f2-1d6bb746516f.png)

Here is one image that produces this result.
It looks like rawData[rawDataCount] produces an int instead of a tuple

**Comment by beurtschipper** [comment]
Ah yes, that image is a greyscale image. It only uses 8 bit per pixel (= 1 integer).

**Comment by OrioPrisco** [comment]
I used the windows screenshot tool (WIN+S) And then pasted it into Paint.net. I guess it automatically detected that saving it as greyscale would be the most optimal
