### ISSUE TITLE
utilisation de DEPIX

### ISSUE THREAD

**Issue by AbderrahmaneDinoune** [beurtschipper/Depix#34]
comment puis-je exécuter ou utiliser l'outil depix.
j'ai télécharger le dossier , mais j'arrive pas a l'utilisé.

**Comment by anasbalkhadir** [comment]
The command is : python depix.py -p [pixelated rectangle image] -s [search sequence image] -o output.png.

Refer to this section: https://github.com/beurtschipper/Depix#usage
