### ISSUE TITLE
Which program could I pixelize my image?

### ISSUE THREAD

**Issue by taurusxin** [beurtschipper/Depix#35]
I wonder if you can commit a program of the pixelize algorithm of depix, actually I have try a lot of software, like PS, or snipaste, depix cannot work correctly, maybe these software's pixelize algorithms are different with depix.

**Comment by beurtschipper** [comment]
Try Greenshot, it should work. I also noticed that tools like Gimp use a very similar pixelization algorithm but their color patterns are slightly shifted. I don't yet know why this is, but I'll try to get it to work in the future.

**Comment by taurusxin** [comment]
> Try Greenshot, it should work. I also noticed that tools like Gimp use a very similar pixelization algorithm but their color patterns are slightly shifted. I don't yet know why this is, but I'll try to get it to work in the future.

Okay! Thank for that, I tried Greenshot, it works. Much more better than what I do recent. Really appreciate your efforts in this project.
