### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by nishuo** [beurtschipper/Depix#37]
`root@~/Depix#` pip3 install pillow
Collecting pillow
  Downloading Pillow-8.0.1-cp37-cp37m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 14.7 MB/s 
Installing collected packages: pillow
Successfully installed pillow-8.0.1
root@:~/Depix# ls
20201226220010.png  depixlib  depix.py  docs  get-pip.py  images  LICENSE  README.md  requirements.txt  s.png
root@~/Depix# python depix.py -p 20201226220010.png -s s.png -o out.png
INFO:root:Loading pixelated image from 20201226220010.png
Traceback (most recent call last):
  File "depix.py", line 27, in <module>
    pixelatedImage = LoadedImage(pixelatedImagePath)
  File "/root/Depix/depixlib/LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "/root/Depix/depixlib/LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object has no attribute '__getitem__'

**Comment by beurtschipper** [comment]
This seems to happen when your image is just greyscale (no rgb but just black-white)
