### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by davidhcefx** [beurtschipper/Depix#38]
There's a double for-loop in `findSameColorRectangle(pixelatedImage, startCoordinates, maxCoordinates)`:

https://github.com/beurtschipper/Depix/blob/5a124f013c7c1ca37a9b3b67cff3ede2a2c24de5/depixlib/functions.py#L29-L35

I noticed that instead of returning **horizontal** rectangles, as described in the comment, it would prefer **vertical** rectangles instead. A simple testcase would be:
```
R R R
R B B
R B B  (R=Red, B=Blue)
```

So, either the comment or the implementation was incorrect. That's what I've found.

**Comment by beurtschipper** [comment]
You're right, thanks! I've added it to the code
