### ISSUE TITLE
Algorithm is low efficiency

### ISSUE THREAD

**Issue by happyapple668** [beurtschipper/Depix#41]
algorithm is low efficiency
pic like 
https://github.com/happyapple668/Depix/blob/main/images/testimages/testimage4.png
and 
https://github.com/happyapple668/Depix/blob/main/images/testimages/testimage4_pixels.png

the test pic cost very very long time with no error
Python version is 3.8.3

**Comment by beurtschipper** [comment]
Well make it faster then
