### ISSUE TITLE
Include the background post from LinkedIn directly in the README.md

### ISSUE THREAD

**Issue by lipis** [beurtschipper/Depix#5]
https://www.linkedin.com/pulse/recovering-passwords-from-pixelized-screenshots-sipke-mellema/

It's super interesting and maybe it can be added in the end as a background.

**Comment by WuerfelDev** [comment]
It's right there at the top 17287b5

**Comment by sickcodes** [comment]
Please add your twitter too :) can't find you easily

**Comment by lipis** [comment]
I mean the actual content of it to be part of the README

**Comment by sickcodes** [comment]
Author's Twitter is here btw: 

https://twitter.com/spibblez
