### ISSUE TITLE
Bug:Program execution problem

### ISSUE THREAD

**Issue by yxl-loading** [beurtschipper/Depix#50]
original image：<img width="308" alt="1234" src="https://user-images.githubusercontent.com/57321692/110190750-c8c0bf00-7e5f-11eb-86af-9d21b2275e69.png">
Program running image：
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/57321692/110191311-92d10a00-7e62-11eb-971e-99b4a89ad886.png">
When some pictures are processed by using this program, the program runs for a long time without results (as shown above). Is this a normal result?

**Comment by yxl-loading** [comment]
Looking forward to your advice

**Comment by beurtschipper** [comment]
I don't know why it takes so long. You should add some debugging lines to the application to check what it's doing.
