### ISSUE TITLE
Not working on Pop!_OS 20.04

### ISSUE THREAD

**Issue by LinuxMinecrafter** [beurtschipper/Depix#56]
This may be an issue with my computer, but I can't get it to run on Pop!_OS 20.04 LTS. Here is the error.

Traceback (most recent call last):
  File "depix.py", line 27, in <module>
    pixelatedImage = LoadedImage(pixelatedImagePath)
  File "/home/[My User]/Depix/depixlib/LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "/home/[My User]/Depix/depixlib/LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object is not subscriptable

**Comment by LinuxMinecrafter** [comment]
Haha I'm an idiot. Nevermind. Had the wrong file path

**Comment by LinuxMinecrafter** [comment]
I'm even more of an idiot. still not working

**Comment by amandesai01** [comment]
Get some sleep.

**Comment by LinuxMinecrafter** [comment]
pffft
