### ISSUE TITLE
'int' object is not subscriptable

### ISSUE THREAD

**Issue by CookidNA** [beurtschipper/Depix#61]
This issue has been posted before but I do not have any success with the fixes provided.

```
C:\Users\cooki\Desktop\repix\Depix>python depix.py -p inputs/green2.png -s images/searchimages/calabri24.png -o outputs/output.png
INFO:root:Loading pixelated image from inputs/green2.png
INFO:root:Loading search image from images/searchimages/calabri24.png
Traceback (most recent call last):
  File "depix.py", line 31, in <module>
    searchImage = LoadedImage(searchImagePath)
  File "C:\Users\cooki\Desktop\repix\Depix\depixlib\LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "C:\Users\cooki\Desktop\repix\Depix\depixlib\LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object is not subscriptable
```

Previous closed issues included the image being 8bit, grayscale and "is in some way broken". 

So to fix I have tried: Saving as 32, 28 bit, pixelating and saving through paint.net, saving the paintnet pixelated version through lightshot, saving the same through greenshot, pixelating and saving with greenshot, and also adding a light colored background to remove grayscale possibilities. Also have tried just writing in notepad with font and size and scing with greenshot and pixelating with greenshot yet same result.

Currently, I am left with these, which is the light bg color version (white bg versions still yield the same error):
![new](https://user-images.githubusercontent.com/53312281/111567135-78553580-876c-11eb-8f41-a4a9151a125e.png)
![sc](https://user-images.githubusercontent.com/53312281/111567149-7b502600-876c-11eb-9218-ea736a0d77aa.png)
![green](https://user-images.githubusercontent.com/53312281/111567346-ccf8b080-876c-11eb-98f4-4b73a3857198.png)
![greened](https://user-images.githubusercontent.com/53312281/111567351-cff3a100-876c-11eb-8fd0-2e55d7769179.png)
(in order, respectively, paint.net pixelated and saved, lightshot SC of paintnet pixelated, greenshot sc of paintnet pixelated, greenshot sc of unpixelated and pixelated in it's editor)

I understand from other submitted issues this bug rises from the image being wrong bits due to color, but clearly that's not the only reason.

**Comment by nicosecci** [comment]
I think the problem depends by the software the image has been saved in and not about its content. The same error used to appear to me as well while saving the image with Paint.net. I have tried to put the image into MS Paint and save it with it and the error didn't appear anymore.

**Comment by beurtschipper** [comment]
What nicosecci said. Please try to do some debugging to see that you're image is greyscale. Or implement a version that works with those images.
