### ISSUE TITLE
How fast is this program?

### ISSUE THREAD

**Issue by aw632** [beurtschipper/Depix#63]
Running `python depix.py -p /images/testimages/testimage2.png -s images/searchimages/debruinseq_notepad_Windows10_closeAndSpaced.png -o /images/testimages/output.png`

seems to yield nothing after "Finding matches in search image"

I am not sure if my PC is just too slow for this program, or if it just takes a long time in general

**Comment by beurtschipper** [comment]
Normally it's 3 fast. I don't know either, maybe you can try and add some debug statements yourself.
