### ISSUE TITLE
The correct term is pixelated, not pixelized.

### ISSUE THREAD

**Issue by azav** [beurtschipper/Depix#73]
The incorrect term is used all through the explanation of the project and read me.  The correct terms are pixelated and depixelated.

**Comment by F8ER** [comment]
Pixelized is a correct word.
> A `pixelized` image is an image that has undergone the pixelization process.
> A `pixelated` image is an image whose resolution allows one to identify the single pixels of the image and in general gives the impression of poor quality.
> Source: <https://www.usenix.org/legacy/event/woot11/tech/final_files/Cavedon.pdf>
