### ISSUE TITLE
I dont understand how to use this

### ISSUE THREAD

**Issue by AnayKumar-08** [beurtschipper/Depix#75]
Hi
I appreciate your hardwork and time but i am not able to figure out how to use this please help

**Comment by iRupam** [comment]
@AnayKumar-08 Can you elaborate on which part(e.g. Python installation, forking, cloning etc) you are actually facing problem? It will help us to help you better.

**Comment by F8ER** [comment]
> Hi
> I appreciate your hardwork and time but i am not able to figure out how to use this please help

<https://dontasktoask.com/>
