### ISSUE TITLE
I dont get how to setup

### ISSUE THREAD

**Issue by bob212** [beurtschipper/Depix#76]

**Comment by Oakchris1955** [comment]
What exactly do you mean @bob212 ?
Also check this website https://dontasktoask.com/

**Comment by bob212** [comment]
@Oakchris1955 i dont know how to set it up

**Comment by Rekunan** [comment]
If you're asking about setting up Depix, have you read the README? Go to https://github.com/beurtschipper/Depix and scroll down. There'll be instructions for installing, setting up, and using Depix.

If you're asking about creating images to test with, I'd recommend downloading a program like [ShareX](https://getsharex.com/) and using the pixelate feature.

**Comment by F8ER** [comment]
> If you're asking about setting up Depix, have you read the README? Go to https://github.com/beurtschipper/Depix and scroll down. There'll be instructions for installing, setting up, and using Depix.
> 
> If you're asking about creating images to test with, I'd recommend downloading a program like [ShareX](https://getsharex.com/) and using the pixelate feature.

Just ignore a possible yet another troll. Consider checking out this repository recent issues. They all lack of normal discussion.
@beurtschipper, I'd recommend disabling the issue creation, temporarily or enabling better moderation, if possible.
