### ISSUE TITLE
TypeError: super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by vdb-sander** [beurtschipper/Depix#8]
A TypeError is shown when the tool is run on a Macbook.

- Python 2.7.16
- Pillow 6.2.2
- MacOS 10.15.7

<img width="1164" alt="Screenshot_2020-12-07_at_11_27_30" src="https://user-images.githubusercontent.com/22551648/101340396-f22d7700-387f-11eb-9b23-8496e130044d.png">

**Comment by vdb-sander** [comment]
In `Depix/depixlib/Rectangle.py` on line 3, `Rectangle` class is not declared as a 'new-style' class. Change that line to:

`class Rectangle(object):`

**Comment by pineappleKID** [comment]
You can also try with python3, which works in my case.
